### ISSUE TITLE
Custom Tooltip function

### ISSUE THREAD

**Issue by mattyjcuk** [LarawireGarage/larapex-livewire#1]
I would like to add a callback function to tooltip.y.formatter using the instruction in ApexCharts... is this possible with larapex-livewire ?

![image](https://github.com/LarawireGarage/larapex-livewire/assets/87066615/bf174201-476d-4487-8dcf-102c1c465dce)

**Comment by LarawireGarage** [comment]
@mattyjcuk , Callback functions cannot use with larapex-livewire package yet... I am working on a solution for that... I might able to implement that soon....

**Comment by LarawireGarage** [comment]
@mattyjcuk I release new minor version v1.2.0 with JS callback functions support feature. Update [LarawireGarage/larapex-livewire](https://github.com/LarawireGarage/larapex-livewire) package and Checkout [Readme](https://github.com/LarawireGarage/larapex-livewire/tree/1.x?tab=readme-ov-file#larapex-livewire) Docs.
